### ISSUE TITLE
Error when decoding Emoji

### ISSUE THREAD

**Issue by lfuelling** [Lynnesbian/mstdn-ebooks#13]
I got an error when running `gen.py` with `--simulate`. Apparently the script fails when trying to decode the "zany-face"-Emoji. 

```
╭─lerk@comm ~/mstdn-ebooks  ‹master*› 
╰─$ python3 ./gen.py --simulate
Traceback (most recent call last):
  File "./gen.py", line 39, in <module>
    print(toot['toot'])
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f92a' in position 100: ordinal not in range(128)
```

Can I ignore invalid characters somehow?

**Comment by Lynnesbian** [comment]
I'm having some trouble reproducing this:
![Python 2 and 3 print emoji fine](https://lynnesbian.space/res/ceres/sshot_2019-02-23_at_10-29-43-1550881783.png)

I do understand what the error is, though. I'll update the script so that if it fails to print the first time, it strips out any non-Unicode characters and tries again.
